Update ury_pos_invoice.py
Removal of theis Error 
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'str'Possible source of error: ury (app)